### ISSUE TITLE
`tx push` issue

### ISSUE THREAD

**Issue by beshrkayali** [transifex/transifex-client#114]
Hey,

I have a project with integrated Transifex cmd client workflow that's been in use for a few months. 

I'm suddenly getting a problem with `tx push -t` returning an incomplete/cut-off error message:

```
Pushing 'fi' translations (file: locale/fi/LC_MESSAGES/django.po)
                                ' does not have enough non-empty translations for all plural forms
```

Trying to bypass this with `tx push -tf` also prints the same incomplete error message.

Edit: I understand what the issue is, it's just strange that there's no indication to where exactly the problem lies and my file is pretty huge I can't dig through it manually...

**Comment by nelefth** [comment]
Hi @beshrkayali, 

Regarding your issue, I assume that your translation file includes untranslated plural entries and that's why you are facing such issues.

Please note that this is a known issue for us and we have already added this to our backlog. 

You can also contact us at support@transifex.com in order to send us your file and properly guide you. 

I would suggest you translate all the **untranslated pluralized strings** and try to upload the file on Transifex.

**Comment by beshrkayali** [comment]
Great, good to know @nelefth! Thanks.

**Comment by nelefth** [comment]
@beshrkayali I just would like to inform you that the issue has been resolved.

**Comment by beshrkayali** [comment]
@nelefth Fantastic, thank you!
