### ISSUE TITLE
What is a resource?

### ISSUE THREAD

**Issue by JulienPalard** [transifex/transifex-client#141]
I'm trying to setup tx client for the [french translation of the python documentation](https://github.com/afpy/python_doc_fr), and I'm hitting some badly documented sections, I'll try to document my failures so you can enhance your documentation.

While reading the [auto local setup documentation](http://docs.transifex.com/client/set/#auto-local-setup) I'm told to use a `resource_slug`, but my project (Python doc translation) have 464 resources according to https://www.transifex.com/python-doc/python-35/content/, so as I won't run 464 commands nor write a script to run your script, I may have read something wrong in the doc, what it is?

**Comment by horus68** [comment]
You should create a local setup file then hit upload source then hit upload translations. Resources (same as files) on Transifex will be created with their translations.

see my documentation for Joomla project, it might help you to understand the system
Creating Transifex Project - Keep Calm and Translate Joomla - https://sites.google.com/site/transjoomla/transifex-for-developers/creating-transifex-project

**Comment by JulienPalard** [comment]
@horus68 Thanks, but won't clik. I'm reporting a bug in the documentation, that's not to read another. The doc is literally telling me to use a "resource slug" but I already have 464 resources. (I'm joining an existing project (python-doc), I'm trying to add another language (french)).

**Comment by horus68** [comment]
That was just me trying to help you on how to use many resources the easy way.
Sometimes we need to read different explanations to understand the logic of a system.
I'm sure you will find a way to use it on your own or just wait for someone from transifex to help you.
Note: I'm not affiliated to the project just a plain user!

**Comment by diegobz** [comment]
@JulienPalard You got it right. Normally if you have several source files in your repo to send to Transifex, you will need to run a command to configure each on of them in the CLI. You just need to do it once though, and people tent to script it when it's a lot of files.

Just so I confirm I got your use case right, you have this repo with french translations which you want to push to projects under the `python-docs` organization in Transifex.

If that's the case. You can eventually configure the CLI tool from Transifex, rather than your local files in the repo. To do so you need to rely on the `--auto-remote` option of the `set` command in client and run it for each project you have.

Keep in mind that the `.tx/config` will have default configuration regarding the path were translations will live, which is under a folder called `translations`. To change that to reflect the file structure of your repo, you will still need to tweak the `.tx/config` file for all the 400+ entries.

Unfortunately there is no silver bullet for this use case. You some how need to create the mapping between the files in your repo and the resources in Transifex.

**Comment by JulienPalard** [comment]
I tried to use `--auto-remote` but [the doc was out of date](https://github.com/transifex/transifex-client/issues/140) (with URI containing `/project/` which look like they does no longer exists). I hope the doc will be fixed soon about those URI formats.
 
> you will still need to tweak the .tx/config file for all the 400+ entries

Like, seriouly? I mean, I know `sed` but tell this to someone who don't?

@horus68 Yup, I understand you're trying to help, which is really nice of you (Thank you), but I'm not trying to get help, I'm just reporting bug. I'm sorry my bug report title was highly misleading about this fact, sorry for that, my bad. And thanks for your help (which actually helped, still hope the documentatil will be fixed, for others).

**Comment by diegobz** [comment]
>> you will still need to tweak the .tx/config file for all the 400+ entries

> Like, seriouly? I mean, I know sed but tell this to someone who don't?

Generally the CLI is meant to be used by developers, so we expect people to be able to script things if they need to. If you have any idea on how this could be improved, please open another ticket or PR just related to it.

As #142 got closed once the docs got updated, I'm closing this one too.
