### ISSUE TITLE
HttpNotAuthorized: Authorization Required

### ISSUE THREAD

**Issue by vkaracic** [transifex/transifex-client#169]
I'm getting this error when trying to either ``tx pull -af`` or ``tx push -s``.

This is my .tx/config:
```
[main]
host = https://www.transifex.com

[googlemapsxblock.textpo]
file_filter = google_maps/translations/<lang>/LC_MESSAGES/text.po
source_file = google_maps/translations/en/LC_MESSAGES/text.po
source_lang = en
type = PO

```

And my ``~/.transifexrc``:
```
[https://www.transifex.com]
hostname = https://www.transifex.com
password = <my_password>
token =
username = <my_username>
```

transifex-client version: 0.12.1
The link to my resource on transifex.com: ``https://www.transifex.com/extensionengine/googlemapsxblock/textpo/``

I'm obviously doing something wrong, but I've exhausted almost all results on google about this error.
Any ideas?

**Comment by nelefth** [comment]
@vkaracic I assume that you are the maintainer of this project and the administrator of the ExtensionEngine organization. So, as an authorized user, you should be able to access the content of your resources. 
Could you please check if there is another .transifexrc file that has been created and used by default?
Also, in order to upgrade to our latest version, use the following command line:
pip install transifex-client==0.12.4

**Comment by vkaracic** [comment]
Yes, I'm currently the maintainer and admin of the EE organization. We're trying out tranisfex with a trial account, could that be why I'm having connection issues? To answer your questions, that is the only transifexrc file that I have on my system. I upgraded to 0.12.4 but I still get that error.

**Comment by nelefth** [comment]
@vkaracic sorry I missed that.

Is this still an issue for you?

Please note that when you encounter issues, you can contact us at support@transifex.com in order to make sure that your request will be processed as soon as possible.

**Comment by bytehead** [comment]
Same problem here. I tried API key and username/password.
