### ISSUE TITLE
one to many language mapping is not working

### ISSUE THREAD

**Issue by hualet** [transifex/transifex-client#176]
As described in the title, one to many language mapping should be working.

For example, I need to map Latin American Spanish (locale es_419)  to a lot other locales like es_ar, es_bo and so on, so Qt can load them properly.

Is this in the plan? or do you accept pull requests?

**Comment by nelefth** [comment]
Hi @hualet,
Spanish (Argentina) (es_AR) & Spanish (Bolivia) (es_BO) are languages that already supported in Transifex.
You can find the whole list [here](https://www.transifex.com/explore/languages/)
So, instead of having the target language es_419, you could add the desired locales as new target languages to your project and pull the corresponding translation files via Client.

Would that be considered as a workaround for you?

**Comment by hualet** [comment]
Of course it’s an option, but the translators of Spanish Latin American may be unhappy about that because Spanish Argentina, Spanish Bolivia are the same as Spanish Latin American to them. I’m just not very sure.

**Comment by diegobz** [comment]
@hualet The language mapping feature is about one to one relations. It's basically a way to set an alias to a language code because of different formatting standards. For example, `pt_BR` vs `pt-br` in file paths. That's really the point.

Having 1-to-many relations is not supported by design. As the CLI takes care of file exchanges between your repo/files and Transifex, the 1 to many concept would potentially create a problem with content being able to be overwritten by mistake.

If you need extra languages with eventually the same content, you can follow @nelefth's suggestion or eventually just create copies of your a file to the desired languages after you download stuff from Transifex. You should write your own script for the second case.
