### ISSUE TITLE
Can't detect RestructuredText file format 

### ISSUE THREAD

**Issue by bmillemathias** [transifex/transifex-client#230]
I'm trying transifex for the project https://github.com/flatpak/flatpak-docs but the command `tx init` cannot suggest me the file format
```
tx -d init
[?] Enter the path to your local source file: docs/getting-started.rst
[?] Enter a path expression: po/<lang>/LC_MESSAGES/getting-setup.po

Here’s a list of the supported file formats. For more information,
check our docs at https://docs.transifex.com/formats/.


[?] Select the file format type [1-0]: 1
Error: Invalid choice. Enter the number corresponding with the format you wish to select.
[?] Select the file format type [1-0]: 0
Error: Invalid choice. Enter the number corresponding with the format you wish to select.
``` 
also it would be better in case the file format is not detected to stop the process with a proper message stating this.

transifex-client 0.13.3

**Comment by rigaspapas** [comment]
Thanks a lot for your feedback! We have implemented a fix that will be included in the next version.

**Comment by bmillemathias** [comment]
Hello,
when you say
> Thanks a lot for your feedback! We have implemented a fix that will be included in the next version.
Are you referring to rst support or better handling of unknown format ?

**Comment by rigaspapas** [comment]
The latter one, we handle unknown formats gracefully. There is an open pull request for this.

Transifex does not support RestructuredText, but since `RST` files are simple text files with lightweight syntax, you can change your files to plain text files (`.txt`) by changing the extension and upload them to Transifex.

After you finish the translations you can download them again as `.txt` and then change the extension to `.rst` without losing any information.

We will definitely take your feedback into consideration for future improvements. In case you need any further assistance, you can always contact our support team at support@transifex.com
