### ISSUE TITLE
Can transifex-client not pin six==1.11.0?

### ISSUE THREAD

**Issue by nedbat** [transifex/transifex-client#252]
It would simplify our installation if transifex-client didn't tightly pin six==1.11.0.  Could it be changed to six>=1.11.0,<2.0 ?

**Comment by flaviotordini** [comment]
MacOS 10.14 comes with six 1.4.1. Supporting that and higher versions would make it easier to install. I had to do `sudo pip install --ignore-installed six==1.11.0` to install transifex-client.

**Comment by lbazan** [comment]
Hi --

Currently is 1.12.0

Cheers,

**Comment by pudo** [comment]
This is breaking our build environment quite badly. Is this client still maintained?

**Comment by beatboxchad** [comment]
This also breaks my builds. It's too specific. Is there any reason not to follow semantic versioning? If your code relies on the 1.0 API, then `six>=1.0,<2.0` should be sufficient because you know that breaking changes won't be introduced until the next major version, but you still get to take advantage of non-breaking improvements, bugfixes, and security fixes as they are released.

**Comment by beatboxchad** [comment]
As it stands, due to the overly-specific version pinning this library is completely incompatible with random other libraries. In my case, it's `graphql-relay`.

Specific version pinning like this should be reserved for application deployments, not libraries that the community uses.

**Comment by beatboxchad** [comment]
For anybody who stumbles upon this on the same path I did (and the ones who came before me), the upstream project I was building on switched from Pipenv to Poetry to manage their dependencies.

Poetry seems to handle this gracefully, and I got unblocked. If software can do it, so can I.

**Comment by si14** [comment]
Hey, do you reckon this can be fixed?

**Comment by diegobz** [comment]
We are working on it at #273. We will try to push it in the next days.
