### ISSUE TITLE
tx delete -r doesn't work

### ISSUE THREAD

**Issue by tjerkw** [transifex/transifex-client#258]
I cannot delete resources.

I have a resouce in project "a". With resource "b".
Then i execute `tx delete -r a.b` and it gives an error:

>>> tx ERROR: Specified resource 'a.b' does not exist.

But it does exist!!!

**Comment by tjerkw** [comment]
I found out you can only delete resources that are defined in your transifex config. Not the resources that are available remote. This doesnt really work well with `tx --branch`

**Comment by Zilus** [comment]
The same here.
I'm looking for a way to delete a branch related translation and been unable to do so.

Another approach, would be to delete by category, for example, deleting all resources pointing to branch "feature".
I can't do that either.

**Comment by emil-olsson** [comment]
We're trying to do the exact same thing. 
This really makes it unpractical to work with branches.

> Another approach, would be to delete by category, for example, deleting all resources pointing to branch "feature".

This, would be awesome ☝️

**Comment by tejbirwason** [comment]
Likewise, is there any workaround?

**Comment by chenrui333** [comment]
Any update on this thread, I have run into the same issue.

**Comment by jdknight** [comment]
A workaround, if it helps.

----

Consider an example where you have an existing/active resource `my-prj-pot` with the most recent translation data and old resource `message-pot` you would like to delete. The contents of `.tx/config` may be as follows:

```
[main]
host = https://www.transifex.com

[my-org.my-prj-pot]
file_filter = <lang>/LC_MESSAGES/my-prj.po
minimum_perc = 0
source_file = my-prj.pot
source_lang = en
type = PO
```

If you want to remove an old resource from the command line (since it does not appear to be possible to always remove a resources from the web UI), append a new section entry which identifies the resource you want to delete:

```
[main]
host = https://www.transifex.com

[my-org.my-prj-pot]
file_filter = <lang>/LC_MESSAGES/my-prj.po
minimum_perc = 0
source_file = my-prj.pot
source_lang = en
type = PO

[my-org.message-pot]
```

(this can be done manually, or by doing a call such as `echo "[my-org.message-pot]" >>.tx/config`)

And if you request a delete, the resource will be removed from the organization as well as the recently duplicated entry in the configuration:

```
tx delete -r my-org.message-pot [--force]
 (or)
python -m txclib delete -r my-org.message-pot [--force]
```

**Comment by nelefth** [comment]
Hi all :) 

As you may already know, [GO CLI](https://github.com/transifex/cli) is the new CLI we released in 2021, and the sunset of the deprecated [transifex-client](https://github.com/transifex/transifex-client) has been scheduled for [Nov 30, 2022](https://community.transifex.com/t/postponing-api-2-0-2-5-and-transifex-client-sunset-date/2759). 

Regarding the issue reported in this thread, I have some updates for you that I think you will find useful.

Specifically, with the [GO CLI](https://github.com/transifex/cli), the challenge mentioned above is addressed by using the delete command described [here](https://github.com/transifex/cli#removing-resources-from-transifex) along with the `--branch ` flag. 

You can watch the video below where you can see how this option is used:


https://user-images.githubusercontent.com/13518557/180709305-e97f63fc-7c56-428c-baad-8932a4f6ccf1.mp4


I hope that this helps you achieve what you want. 

For any questions, please do not hesitate to contact us.
