### ISSUE TITLE
Allow for getting the translator names of each language quickly

### ISSUE THREAD

**Issue by tobbi** [transifex/transifex-client#274]
I'm currently updating the credits of our own project and I find myself skimming through the list of .po files to find out who translated which file. 

It'd be nice if the tx client offered a way to get the list of translators for each language.

**Comment by pankav** [comment]
Hello Tobbi,

Thank you for submitting your request.

Unfortunately, what you are looking for is not offered via TX Client. However, Transifex offers translation activity reports that include all the translators' translation activity during a specific time internal.

You can find more information about this feature in our documentation guide here:https://docs.transifex.com/tracking/reports#using-reports. However, please note that Reports is a feature available on the Advanced plan and up.

If this feature is not available in your account due to the plan you have subscribed to, then the only option is to use our API endpoint described here: https://docs.transifex.com/api/languages#translators that returns a JSON list of translators usernames that belong to your translation team (the results are not related to their activity though).

Please let me know if you need any additional clarification or assistance.

Regards,
