### ISSUE TITLE
Error received from server: Could not import file: Invalid plural types for string

### ISSUE THREAD

**Issue by aseegobin** [transifex/transifex-client#341]
`transifex-client-0.14.4` started failing suddenly (12:20 PM EST) with the following error:
```
Error: Command failed: tx  push -t -l fr_CA 
tx ERROR: Error received from server: Could not import file: Invalid plural types for string: redacted::team::project::feature::key. Language supports: ['one', 'many', 'other'], but found: ['one', 'other'] instead.
```

Example string: `"{quantity, plural, one {1 action} other {# actions}}"`

Nothing has changed on our end and our build was passing as recent as 11 AM EST. Let me know if there is more information you require.

Can you confirm if anything has changed on your end between the hours of 11AM EST and 12:20PM EST which result in our builds failing?

**Comment by aseegobin** [comment]
I just made a change to address the errors and I'm getting the opposite error:
```
tx ERROR: Error received from server: Invalid plural types for string: redacted::team::project::feature::key. Language supports: ['one', 'other'], but found: ['one', 'many', 'other'] instead.
```

New string: `{quantity, plural, one {1 action} many{# actions} other {# actions}}`

**Comment by pankav** [comment]
Hello @aseegobin ,

Thank you for your message.  Is this is still an issue for you?

**Comment by aseegobin** [comment]
Hi @pankav thank you for responding. Yes, it is still an issue for our team. We are still getting the errors as stated above

**Comment by aseegobin** [comment]
Quick update - we reran our build 10 minutes ago and it has passed. It seems like the issue has been fixed. Can you give us any insight on what changed?

**Comment by pankav** [comment]
Sure @aseegobin .
﻿
﻿Regarding your question, I would like to inform you that this change happened due to mistaken deployment from our side, and I truly apologize for this. 
The mistaken deployment was related to the new 3 available formats for plurals in the French language.

Now, as you confirmed, it should be ok again with the two plural forms (1, other).

However, I would like to inform you that, there will be a 1month-notice before taking these changes to live since, for the plurals for the French language, there is a new third form based on the [CLDR rules](https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html?utm_source=hs_email&utm_medium=email&utm_content=40767534&_hsenc=p2ANqtz-_8_VToT4MKEMVcpIOVkSIdByzjRlzHI67N8xoXqwNNoIcJLjvBP2KvwxjsBV5jhO9qn42B_ReN4OzdJnMqdX4IZLzvWg&_hsmi=40767534)  v.41.0.

![image](https://user-images.githubusercontent.com/55692244/162058127-9b402af3-96cb-4680-9831-c786aa8b5d52.png)


I would like to mention also, that this is not the one-month notice yet.
You will be informed accordingly. Probably, in the next few days, we will make an announcement.

Please let me know if you have any further questions.
﻿
﻿Kind regards,
﻿Panagiotis

**Comment by aseegobin** [comment]
Thank you @pankav for the explanation 👍 . I will take this information back to my team and close this issue out.
