### ISSUE TITLE
Define trusted SSL certificate through transifex-client

### ISSUE THREAD

**Issue by Phoul** [transifex/transifex-client#91]
Currently, transifex-client inherits its SSL trust from the system's trust store. 

This means that the system the client is running on must globally trust the root that Transifex uses. Being able to define a trusted certificate directly with transifex-client would allow the certificate to only be trusted for transifex-client usage.

**Comment by effigies** [comment]
Is this a request to restrict the root CAs to the one that Transifex uses, or for the actual certificate to be specified? There seem to be a few considerations:

1. If this program is distributing its own certificate (or the root cert of its chain), then the rogue CA problem is mitigated, but now this program is in the position of bootstrapping its own trust. It seems like this is [already the case](https://github.com/transifex/transifex-client/blob/master/txclib/cacert.pem) under [some conditions](https://github.com/transifex/transifex-client/blob/master/txclib/web.py#L15), so maybe that's not a huge issue. Either way, the advantages of system-trust are (a) root-owned (b) independently provided.
2. The configuration seems to allow for a non-transifex.(com|net) host to be specified, which makes a restricted bundle of certs liable to break things, if this is a thing people ever do. Making another config option for trusted certificates is an option, but now your trust is all wrapped up in your config file.
3. If a root certificate is hard-coded, the version of the program is good only as long as transifex continues using that CA. If the leaf certificate(s) is(/are) hard-coded, then the version of the program is good only as long as those certs are available.

All that said, if you just want to pare down to the GlobalSign CA, the steps should be as follows:

1. Pare [txclib/cacert.pem](https://github.com/transifex/transifex-client/blob/master/txclib/cacert.pem) to the GlobalSign certs.
2. Update [txclib/web.py:certs_file](https://github.com/transifex/transifex-client/blob/master/txclib/web.py#L15) to always return the built-in cert file instead of searching for the system bundle.
3. Never change the hostname in your config file.

**Comment by amanatidis** [comment]
@Phoul, @effigies 

We created a branch:  https://github.com/transifex/transifex-client/tree/custom-ca-cert. In this branch after the `tx` command you can provide a `cacert` argument. For example:

    tx --cacert=/path/to/ca/file pull -a

Can you try it and provide feedback?
